server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.206.66:9300
  jackson: #声明消息转换器在对对象转换是，如果对象的属性的值为null则不纳入结果
    default-property-inclusion: non_null

  rabbitmq:
    virtual-host: /heihei
    host: 192.168.206.66
    username: heima62
    password: heima62

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}